# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    #指定接口全局api
    context-path: /api

# spring基本配置
spring:
  application:
    name: user-center

  #mysql配置信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/beihong
    username: root
    password: root

  #session超时时间
  session:
    timeout: 64800

mybatis-plus:
 configuration:
   map-underscore-to-camel-case: false
   #sql执行日志
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

 global-config:
    db-config:
      logic-delete-field: idDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)